version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - .:/srv/app

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=jdoe
      - MARIADB_DATABASE=application
      - MARIADB_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
       - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mariadb:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: jdoe
        MYSQL_PASSWORD: secret

volumes:  
  db_data:
